#!/usr/bin/with-contenv bash

# install mcmyadmin2
if [ ! -e /minecraft/MCMA2_Linux_x86_64 ];
	then
	echo "
	**********************************************************
	Installing Mcmyadmin & Vanilla Minecraft,
	this will only take a few minutes
	**********************************************************
	"
	cp -v /opt/mcmyadmin2/*  /minecraft/MCMA2_Linux_x86_64
	chmod +x /minecraft/MCMA2_Linux_x86_64
	cd /minecraft || exit
	./MCMA2_Linux_x86_64 -setpass password -nonotice -configonly
fi

# permissions
chown -R abc:abc /minecraft
